version: '3'

services:

  skyblock-stats:
    build: .
    restart: always
    container_name: skyblock-stats
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    environment:
      API_KEY: 80050a61-5f10-4ce4-85de-1915c44b4459
      VIRTUAL_HOST: skyblock.physanus.io
      LETSENCRYPT_HOST: skyblock.physanus.io
      LETSENCRYPT_EMAIL: letsencrypt@danielprinz.de
    networks:
      - default

